apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickdelivery
  labels:
    app: quickdelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickdelivery
  template:
    metadata:
      labels:
        app: quickdelivery
    spec:
      containers:
        - name: quickdelivery
          image: 271153858532.dkr.ecr.ap-southeast-1.amazonaws.com/admin21-flower-quickdelivery:v1 
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5